### ISSUE TITLE
Synching configurable products with multiselect attributes throwing error

### ISSUE THREAD

**Issue by JamesFX2** [clerkio/clerk-magento2#80]
Issue is caused by 

https://github.com/clerkio/clerk-magento2/blob/master/Model/Adapter/AbstractAdapter.php#L170

```
PHP Warning:  Array to string conversion in /home/cloudpanel/htdocs/www.example.com/releases/2022_09_07_4_25_31_branch_v2.4.4-3/vendor/clerkio/magento2/Model/Adapter/AbstractAdapter.php on line 170
```

I looked at the format of data and it looked like this

```
Array
(
    [0] => Array
        (
            [0] => Ethinylestradiol
            [1] => Progestogen
        )

    [1] => Array
        (
            [0] => Ethinylestradiol
            [1] => Progestogen
        )

    [2] => Array
        (
            [0] => Ethinylestradiol
            [1] => Progestogen
        )

)

```

So it's throwing an error synching multiselect attributes which return their value as an array. You're going to need to use an array filter to implement uniqueness or implode and then explode the data.

**Comment by FoulBachelor** [comment]
Hi James,

I have added a array_walk method which recursively flattens all attribute outputs for configurable and grouped products. 

https://github.com/clerkio/clerk-magento2/commit/dc0428d3206ce03cb24d22e5b1c0ff3f70d15560

This will be included in the next release.

**Comment by JamesFX2** [comment]
@FoulBachelor I just looked at 4.6.2, I think \Clerk\Clerk\Model\Config is missing a const for XML_PATH_PRODUCT_SYNCHRONIZATION_ENABLE_ORDER_RETURN_SYNCHRONIZATION as well as the system.xml value. Do you need a separate ticket?

**Comment by FoulBachelor** [comment]
It is due to order returns being tied to a separate settings being a feature which is not complete yet. 

We are looking to tie the control of module settings into our online dashboard, in my.clerk.io, but the feature isn't slated for use / implementation yet.

The next release at the end of the current cycle should include the final implementation of get/set config which this will be used for.

**Comment by FoulBachelor** [comment]
It has been in the code base for the past couple of releases.

Has this caused you an issue on your site, given that the function is not called and is wholly unrelated to the retrieval of product attributes we were looking at in this issue?

**Comment by JamesFX2** [comment]
> Has this caused you an issue on your site, given that the function is not called and is wholly unrelated to the retrieval of product attributes we were looking at in this issue?

I'm sorry if my comment upset you. To be honest, I hadn't noticed that there wasn't an event associated with it. You can be sarcastic if you want but, 

> It is due to order returns being tied to a separate settings being a feature which is not complete yet.

You know that this is typically what feature branches are used for! 

I hadn't noticed that this was added in 4.6.0 because I was comparing 4.5.3 to 4.6.2. We have to do adaptations on what we send back to your servers so a new observer like this will have to be intercepted when it finally goes live. We look at anything that might affect this. 

There have been historic issues (including this ticket) where a new version of the Clerk extension has been released and caused issues so please forgive me for assuming the worst. I'm glad to be wrong. Thanks @FoulBachelor

**Comment by FoulBachelor** [comment]
Hi James,

I apologize if I seemed annoyed, but my question was actually genuine. 

Even though in my view the issue was not throwing any error, and did not seem related to the ticket I was genuinely curious if it was causing you trouble. 

This current release was pushed by me, due to it containing mainly stability bugfixes which were important to not delay.

I also agree with you that it would be clearer for an outside observer, if code which is not in use is simply not present in the release. 

That said, I am not the Dev in charge of completing the feature in question, hence my apprehension for modifying it's current presence without having an error to justify the removal.

I hope this makes sense, and thank you for taking the time to submit your feedback. It is honestly appreciated, and is very helpful in delivering the stability we would like to see in the module.

Let me know if you run into anything else, but otherwise I hope that the updates are making a positive impact. ❤️
